"""fixed the default is_accomplished for lakshya

Revision ID: 54a2cedcbaaa
Revises: 7e1e574f13cb
Create Date: 2026-05-06 00:10:13.350636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54a2cedcbaaa'
down_revision: Union[str, Sequence[str], None] = '7e1e574f13cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
