"""added is_accomplished and deadline to lakshya

Revision ID: 7e1e574f13cb
Revises: 894c671cb78f
Create Date: 2026-05-05 23:23:20.790469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e1e574f13cb'
down_revision: Union[str, Sequence[str], None] = '894c671cb78f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lakshya', sa.Column('is_accomplished', sa.Boolean(), nullable=False,server_default=sa.text('false')))
    op.add_column('lakshya', sa.Column('deadline', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lakshya', 'deadline')
    op.drop_column('lakshya', 'is_accomplished')
    # ### end Alembic commands ###
