"""make email unique

Revision ID: 894c671cb78f
Revises: 8b041b499342
Create Date: 2026-05-03 23:11:08.042310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '894c671cb78f'
down_revision: Union[str, Sequence[str], None] = '8b041b499342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_khiladi_email'), 'khiladi', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_khiladi_email'), table_name='khiladi')
    # ### end Alembic commands ###
