"""add_otp_columns

Revision ID: 8b041b499342
Revises: cf32ac77baa6
Create Date: 2026-05-03 18:45:15.320040

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b041b499342'
down_revision: Union[str, Sequence[str], None] = 'cf32ac77baa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('khiladi', sa.Column('is_verified', sa.Boolean(), nullable=False,server_default=sa.text('false')))
    op.add_column('khiladi', sa.Column('otp_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('khiladi', sa.Column('otp_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('khiladi', 'otp_expires_at')
    op.drop_column('khiladi', 'otp_code')
    op.drop_column('khiladi', 'is_verified')
    # ### end Alembic commands ###
