"""genesis_cloud

Revision ID: f2bc4b5808fd
Revises: 
Create Date: 2026-05-12 19:18:19.480595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f2bc4b5808fd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('khiladi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('total_xp', sa.Integer(), nullable=False),
    sa.Column('xp_debt', sa.Integer(), nullable=False),
    sa.Column('clan_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('otp_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('otp_expires_at', sa.DateTime(), nullable=True),
    sa.Column('pro_user', sa.Boolean(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_streak_date', sa.Date(), nullable=True),
    sa.Column('streak_freezes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_khiladi_email'), 'khiladi', ['email'], unique=True)
    op.create_index(op.f('ix_khiladi_username'), 'khiladi', ['username'], unique=True)
    op.create_table('lakshya',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_accomplished', sa.Boolean(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('khiladi_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['khiladi_id'], ['khiladi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kaam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', 'epic', name='kaamdifficulty'), nullable=False),
    sa.Column('is_urgent', sa.Boolean(), nullable=False),
    sa.Column('requires_verification', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_review', 'completed', 'rejected', name='kaamstatus'), nullable=False),
    sa.Column('saboot_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('saboot_image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ai_feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('penalty_xp', sa.Integer(), nullable=False),
    sa.Column('has_been_penalized', sa.Boolean(), nullable=False),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('lakshya_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lakshya_id'], ['lakshya.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kaam_title'), 'kaam', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kaam_title'), table_name='kaam')
    op.drop_table('kaam')
    op.drop_table('lakshya')
    op.drop_index(op.f('ix_khiladi_username'), table_name='khiladi')
    op.drop_index(op.f('ix_khiladi_email'), table_name='khiladi')
    op.drop_table('khiladi')
    # ### end Alembic commands ###
